### PR TITLE
Only store each downloaded chunk once

### PR DESCRIPTION
**Pull request by felixbuenemann**
This makes sure the download callback is only run once. This reduces memory pressure, lock contention and cpu usage for storing chunks.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
A small explanation: The same chunk can be requested multiple times, but it is downloaded only once. Each time that the chunk is requested a callback is passed, to store the chunk into the in-memory chunk storage. If we call all callbacks, the same chunk is stored many times over and over.

The new logic just keeps the last callback, since we only have a single codepath and a single callback (that stores the chunk), so there's no need to have a callback chain.

**Comment by felixbuenemann** [comment]
@dweidenfeld It would be great to get your thoughts on this.

I have a local feature branch that implements a mmapped backing store for the chunk cache and I noticed that chunks were stored over and over again while developing it, sometimes 10 times for the same chunk.

This also happens with the current memory only cache and causes quite some stress on the garbage collector, because the same chunk gets stored and evicted multiple times in a row.

I'm not sure if this last-callback-wins change is the right solution to the problem, maybe you've got a better idea.

**Comment by dweidenfeld** [comment]
i totally understand your approach, but what happens if two users are requesting the same chunk almost the same time? wouldn't the first callback win and the other one will never get notified, that his chunk is ready?

**Comment by felixbuenemann** [comment]
I realized this is the wrong approach, since the callbacks are also used to return requested sub-chunks of a chunk, bypassing the cache.

What we can do is an early abort, if the chunk already exists in cache and replacing the global lock on storage with an rwmutex, so we can have many parallel readers of chunks, but only one writer.

If we really wanted to dedup the callbacks, we could turn them into a map indexed by the actual from/to offset, instead of the normalized chunk offset used for downloading.

**Pull request closed without merging**
